### ISSUE TITLE
Hang after successful mount

### ISSUE THREAD

**Issue by noaho** [rhansen/unlock-cryptroot#1]
Hey @rhansen, 

Great script, I used it fine on 15.10. After dist-upgrade to 16.04, after I run the script it works (mounting the drive) but then tries again and again to mount it, and can't, because it already exists. Not sure what I have to change. If I log in with -l and do it manually, it works and the system boots. 

```
checking if /scripts/local-top/cryptroot is running...
getting /sbin/cryptsetup command-line arguments...
command: /sbin/cryptsetup -T 1 --allow-discards open --type luks /dev/mapper/4TBDataMirror-sda1 lvroot_crypt --key-file=-
Enter passphrase:
passphrase accepted; killing passphrase prompt...
  checking for /lib/cryptsetup/[a]skpass...
    killing PID 344...
  checking for [a]sk-for-password...
getting /sbin/cryptsetup command-line arguments...
command: /sbin/cryptsetup -T 1 --allow-discards open --type luks /dev/mapper/4TBDataMirror-sda1 lvroot_crypt --key-file=-
trying previously entered passphrase...
Device lvroot_crypt already exists.
ERROR: '/sbin/cryptsetup -T 1 --allow-discards open --type luks /dev/mapper/4TBDataMirror-sda1 lvroot_crypt --key-file=-' failed
Enter passphrase:
```

Cheers,
Noah

**Comment by rhansen** [comment]
Thank you for the bug report, and I apologize for taking so long to respond.

The `askpass` utility from the `cryptsetup` package that comes with 16.04 is behaving like it is catching or ignoring SIGTERM.  There are two strange things about this:  (1) the `cryptsetup` package hasn't changed since 15.10, and (2) I don't see anything in `askpass.c` that attempts to ignore or catch the SIGTERM signal.  If I use SIGKILL instead of SIGTERM then the script works as expected.

I don't like to use SIGKILL because it doesn't give the utility a chance to clean up (which might be important in this case because `askpass` has some sort of systemd integration).  Until I figure out a cleaner solution, you can pass `-KILL` to the `kill` command to work around this problem:

```
diff --git a/unlock-cryptroot b/unlock-cryptroot
index 79dfd59..38e3810 100755
--- a/unlock-cryptroot
+++ b/unlock-cryptroot
@@ -162,7 +162,7 @@ EOF
         ap_pid=$(getpid "${ap}") || exit 1
         [ -n "${ap_pid}" ] || continue
         log "    killing PID ${ap_pid}..."
-        try kill "${ap_pid}"
+        try kill -KILL "${ap_pid}"
     done
 done
 '
```

Recent versions of the `cryptsetup` package (going back to at least trusty) support reading the password from a FIFO.  That's a much cleaner way to unlock from remote, and it would not suffer from this problem.  Hopefully I'll have some time soon to adjust the script to use that method.

**Comment by noaho** [comment]
Thanks for your reply! I'll probably stick to the manual method for now, I'm wary of breaking a server I don't have easy access to.

**Comment by rhansen** [comment]
I finally updated the script to simply use SIGKILL as described in my post above.  It's not as clean as I would like but it works.
